- name: Initial system setup
  hosts: server

  tasks:
    - name: Make sure ssh service is enabled upon system boot
      service: name=ssh enabled=yes
    
    - name: Create Admin Group
      group: name=admin state=present

    - name: Create Admin User
      user:
        name: admin
        group: admin
        home: /home/admin
        password:  $6$keUjotc09V0$5jgzOGSkfZHGxngDHf7dLQsk0gzyRpAEErQSTgvXsedzMICQ.TSr6sCoSGm8LCJwBKF/wEAXKCxq5cCP4emRM1
        shell: /bin/bash
        state: present

    - name: Install TFTP server packages
      package: name=tftpd-hpa state=present
    
    - name: Configure TFTP Server for write access
      lineinfile: 
        path: /etc/default/tftpd-hpa
        line: 'TFTP_OPTIONS="--secure --verbose -4 -c"'
        state: present
    
    - name: Configure /var/lib/tftpboot permissions
      file: path=/var/lib/tftpboot owner=root group=tftp mode=0775
    
    - name: Start tftpd-hpa service and enable it upon system boot
      service: name=tftpd-hpa state=restarted enabled=yes
